feat: send an ics file in an invitation mail
HybridPlanner/backend pull request #62
Opened 2023-11-06 20:28 UTC by jvondermarck

- Closes #50

2023-11-06 20:32 UTC, Bricklou commented on src/mail/mail.module.ts
> +        host: 'localhost',
Peut-être mettre en place une variable d'environnement pour éviter de modifier à chaque fois ?
(et par exemple mettre une valeur par défaut si la variable est vide)

2023-11-06 20:32 UTC, Bricklou commented on src/mail/mail.service.ts
> +      ),
Pas possible de faire un envoi de mail groupé ? (plusieurs destinataires cachés avec CCI)

2023-11-06 20:32 UTC, Bricklou commented on src/utils/ics-util.ts
> +    console.log('Error creating ics file');
au lieu d'utliser `console.log` plutôt utiliser le Logger NestJS, de sorte à rester cohérent sur notre manière de logger les infos

2023-11-06 20:35 UTC, jvondermarck commented on src/utils/ics-util.ts
> +    console.log('Error creating ics file');
✅

2023-11-06 20:48 UTC, jvondermarck commented on src/mail/mail.service.ts
> +      ),
✅

2023-11-06 20:49 UTC, Bricklou commented on src/mail/mail.service.ts
> +    const url = `http://localhost:5173/meeting/${meeting.id}`;
au lieu d'encoder en dur l'url du frontend, pourquoi ne pas passer une variable d'environnement ?

2023-11-06 20:49 UTC, Bricklou commented on src/utils/ics-util.ts
> +    url: `http://localhost:5173/meeting/${meeting.id}`,
pareil ici: variable d'environnement pour l'hôte

2023-11-06 20:56 UTC, jvondermarck commented on src/mail/mail.module.ts
> +        host: 'localhost',
✅

2023-11-06 21:00 UTC, jvondermarck commented on src/mail/mail.service.ts
> +    const url = `http://localhost:5173/meeting/${meeting.id}`;
✅

2023-11-11 21:07 UTC, samymsa requested changes
- Créer un `ICSService` et l'injecter plutôt que de faire un `utils`.
- Créer le type `MeetingWithAttendees` pour retirer la dépendance sur `DatabaseService`

2023-11-11 21:07 UTC, samymsa commented on src/utils/ics-util.ts
> +export async function createIcsFile(
Ce serait plus propre de créer un `ICSService` et de l'injecter dans `MailService`

2023-11-11 21:07 UTC, samymsa commented on src/mail/mail.service.ts
> +    const meetingWithAttendees = await this.database.meeting.findUnique({
Je ne pense pas qu'interagir avec la base de donnée fasse partie des responsabilités du `MailService`. Il faudrait plutôt définir le type `MeetingWithAttendees` et en passer une instance à cette fonction. Ce sera aux services qui utilisent cette fonction de charger d'abord les `attendees` avec un `include`. Ca enlèvera la dépendance sur le `DatabaseService`.

2023-11-11 21:07 UTC, samymsa commented on src/mail/mail.module.ts
> +  providers: [MailService, DatabaseService],
Voir mon autre commentaire concernant la dépendance sur le `DatabaseService`.

2023-11-13 13:50 UTC, samymsa approved these changes

2023-11-13 13:50 UTC, merged